import type {
  AnyStrategyDefinition,
  DiagnoseRequest,
  DiagnosisView,
  StrategyDraft,
} from '../api/types.ts';

export const capabilityFixture: readonly AnyStrategyDefinition[] = [{
  archetype: 'ma-cross',
  displayName: 'Moving Average Crossover',
  description: 'Trend-following moving-average crossover.',
  parameters: [
    {
      key: 'fastMA',
      label: 'Fast MA',
      description: 'Fast moving-average period.',
      kind: 'integer',
      minimum: 2,
      defaultValue: 8,
    },
    {
      key: 'slowMA',
      label: 'Slow MA',
      description: 'Slow moving-average period.',
      kind: 'integer',
      minimum: 3,
      defaultValue: 30,
    },
    {
      key: 'leverage',
      label: 'Leverage',
      description: 'Position leverage.',
      kind: 'number',
      minimum: 1,
      maximum: 20,
      defaultValue: 10,
    },
    {
      key: 'stopLossPct',
      label: 'Stop loss',
      description: 'Stop-loss fraction.',
      kind: 'number',
      minimum: 0,
      maximum: 0.99,
      exclusiveMinimum: true,
      defaultValue: 0.5,
    },
    {
      key: 'positionPct',
      label: 'Position size',
      description: 'Position fraction.',
      kind: 'number',
      minimum: 0,
      maximum: 1,
      exclusiveMinimum: true,
      defaultValue: 1,
    },
  ],
  example: {
    id: 'ma-example',
    name: 'MA example',
    archetype: 'ma-cross',
    params: {
      fastMA: 8,
      slowMA: 30,
      leverage: 10,
      stopLossPct: 0.5,
      positionPct: 1,
    },
    universe: ['BTCUSDT'],
    timeframe: '1h',
  },
}];

export const draftFixture: StrategyDraft = {
  strategy: {
    id: 'draft-ma',
    name: 'Draft MA',
    archetype: 'ma-cross',
    params: {
      fastMA: 8,
      slowMA: 30,
      leverage: 10,
      stopLossPct: 0.5,
      positionPct: 1,
    },
    universe: ['BTCUSDT'],
    timeframe: '1h',
  },
  source: 'rules',
  confidence: 0.9,
  assumptions: [{
    field: 'strategy.params.positionPct',
    value: 1,
    reason: 'registered-default',
  }],
  warnings: [],
};

export const requestFixture: DiagnoseRequest = {
  strategy: draftFixture.strategy,
  style: 'conservative',
  seed: 42,
  candidates: 6,
};

export const diagnosisFixture = {
  scorecard: {
    strategyId: 'draft-ma',
    scenarioSetId: 'tx42/ho100042',
    perStyle: {
      conservative: {
        style: 'conservative',
        riskScore: 42,
        survived: false,
        worstDrawdownPct: 0.42,
        meanPnlPct: -0.1,
      },
      aggressive: {
        style: 'aggressive',
        riskScore: 55,
        survived: false,
        worstDrawdownPct: 0.42,
        meanPnlPct: -0.1,
      },
      trend: {
        style: 'trend',
        riskScore: 50,
        survived: false,
        worstDrawdownPct: 0.42,
        meanPnlPct: -0.1,
      },
    },
    evaluations: [
      'sentiment',
      'macro',
      'market-intel',
      'news',
      'technical',
    ].map((dimension, index) => ({
      scenarioId: `scenario-${index}`,
      scenarioName: `${dimension} stress`,
      dimension,
      sourceSkill: `${dimension}-skill`,
      severity: index + 1,
      shock: {
        kind: 'crash',
        magnitude: 0.2,
        durationBars: 20,
        volMult: 1.5,
        seed: index,
      },
      metrics: {
        pnlPct: -0.1 * index,
        maxDrawdownPct: 0.2 + index * 0.05,
        liquidated: index === 4,
        numTrades: index + 2,
        equityCurve: [1, 0.9, 0.8],
        drawdownCurve: [0, 0.1, 0.2],
        turnoverPct: 1.2 + index * 0.2,
        feeCostPct: 0.001 + index * 0.0002,
        slippageCostPct: 0.0008 + index * 0.0002,
      },
      cause: index === 4 ? 'liquidation' : 'drawdown-breach',
      damageScore: 50 + index * 10,
      narrative: `${dimension} narrative`,
    })),
    deaths: [],
    prescription: {
      changes: {
        leverage: 5,
        stopLossPct: 0.1,
      },
      rationale: 'Lower leverage and tighten the stop loss.',
      patchedStrategy: {
        ...draftFixture.strategy,
        params: {
          ...draftFixture.strategy.params,
          leverage: 5,
          stopLossPct: 0.1,
        },
      },
    },
    tradeoff: {
      robustnessGain: 12,
      returnCost: -0.02,
    },
  },
  summary: {
    riskScore: 42,
    worstDrawdownPct: 0.42,
    totalTrades: 27,
    totalTurnoverPct: 8,
    feeCostPct: 0.007,
    slippageCostPct: 0.006,
    robustnessGain: 12,
    returnDelta: -0.02,
  },
  riskDashboard: {
    trendScore: 50,
    defenseScore: 38,
    costEfficiency: 0.5,
    trendDefenseGap: 12,
    costEfficiencyThreshold: 1,
    trendThreshold: 35,
    defenseThreshold: 42,
    alerts: [
      {
        code: 'defense-threshold',
        severity: 'warning',
        message: 'defense score is below the threshold',
        value: 38,
        threshold: 42,
      },
      {
        code: 'cost-efficiency-threshold',
        severity: 'warning',
        message: 'cost-efficiency is below the threshold',
        value: 0.5,
        threshold: 1,
      },
    ],
  },
  strategyReview: {
    reviewer: 'local-rule-reviewer',
    mode: 'rules',
    score: 64,
    agreementRate: 1,
    objections: [
      'Worst drawdown is above 50%, so capital survival is weak.',
    ],
    recommendations: [
      'Reduce exposure or add a regime filter before deployment.',
    ],
    summary:
      'The strategy is diagnosable but still needs risk review before deployment.',
  },
  charts: {
    treatmentEquity: [
      { dimension: 'sentiment', equity: [1, 0.9, 1.1] },
      { dimension: 'macro', equity: [1, 0.8, 0.85] },
      { dimension: 'market-intel', equity: [1, 0.7, 0.75] },
      { dimension: 'news', equity: [1, 0.6, 0.65] },
      { dimension: 'technical', equity: [1, 0.5, 0.55] },
    ],
    treatmentDrawdown: [
      { dimension: 'sentiment', drawdown: [0, 0.1, 0] },
      { dimension: 'macro', drawdown: [0, 0.2, 0.15] },
      { dimension: 'market-intel', drawdown: [0, 0.3, 0.25] },
      { dimension: 'news', drawdown: [0, 0.4, 0.35] },
      { dimension: 'technical', drawdown: [0, 0.5, 0.45] },
    ],
    heldOutComparison: [
      {
        dimension: 'sentiment',
        original: [1, 0.8, 0.9],
        patched: [1, 0.9, 1.02],
      },
      {
        dimension: 'technical',
        original: [1, 0.5, 0.6],
        patched: [1, 0.75, 0.88],
      },
    ],
    defaultHeldOutDimension: 'technical',
    riskRadar: [
      { dimension: 'sentiment', value: 30 },
      { dimension: 'macro', value: 40 },
      { dimension: 'market-intel', value: 50 },
      { dimension: 'news', value: 60 },
      { dimension: 'technical', value: 70 },
    ],
    parameterChanges: [
      { key: 'leverage', label: 'Leverage', before: 10, after: 5 },
      { key: 'stopLossPct', label: 'Stop loss', before: 0.5, after: 0.1 },
    ],
    scenarioTimeline: [
      {
        dimension: 'technical',
        scenarioName: 'Technical whipsaw',
        damageScore: 90,
        cause: 'liquidation',
        pnlPct: -0.9,
        maxDrawdownPct: 0.99,
        turnoverPct: 1.8,
      },
      {
        dimension: 'news',
        scenarioName: 'News gap',
        damageScore: 70,
        cause: 'drawdown-breach',
        pnlPct: -0.4,
        maxDrawdownPct: 0.5,
        turnoverPct: 1.2,
      },
    ],
    executionQuality: [
      {
        dimension: 'sentiment',
        scenarioName: 'Sentiment squeeze',
        turnoverPct: 1.2,
        feeCostPct: 0.001,
        slippageCostPct: 0.0008,
        numTrades: 2,
      },
      {
        dimension: 'technical',
        scenarioName: 'Technical whipsaw',
        turnoverPct: 1.8,
        feeCostPct: 0.0014,
        slippageCostPct: 0.0012,
        numTrades: 6,
      },
    ],
  },
} as unknown as DiagnosisView;
